app_infos_periph:
    resource: "@AppBundle/Controller/InfosPeriphController.php"
    type:     annotation

app_parametre:
    resource: "@AppBundle/Controller/ParametreController.php"
    type:     annotation

analytics:
    resource: "@AnalyticsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"