# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AcmeBundle/Acme/User/LdapUser: plaintext

    role_hierarchy:
        ROLE_FACTU: ROLE_USER
        ROLE_RACCO: ROLE_USER
        ROLE_ADMIN: ROLE_RACCO
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_FACTU, ROLE_RACCO]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout_on_user_change : true
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:     /login
                check_path:     /login_check

                always_use_default_target_path: true
                default_target_path: /
            logout: true
            anonymous: true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/user, role: ROLE_USER }

        - { path: ^/factu, role: ROLE_FACTU }

        - { path: ^/tp, role: ROLE_RACCO }
        - { path: ^/parametre, role: ROLE_RACCO }
        - { path: ^/infosperiph, role: ROLE_RACCO }
        - { path: ^/racco, role: ROLE_RACCO }

        - { path: ^/admin, role: ROLE_ADMIN }

        - { path: ^/adminapp, role: ROLE_SUPER_ADMIN }
